# Generated by Django 5.0.7 on 2024-09-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("betago", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaivarity",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
