# Generated by Django 5.0.7 on 2024-09-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("betago", "0002_alter_chaivarity_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivarity",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
